//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;

    public partial class Cisterna : Vozilo
    {
        public Cisterna()
        {
        }

        public Cisterna( string marka, string model, int tip, int godiste, double nosivost, int? id_VatrogasneJedinice) : base(marka, model, tip, godiste, nosivost, id_VatrogasneJedinice)
        {
        }
    }
}
