//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intervencija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intervencija()
        {
            this.RadniciSaSmenama = new HashSet<RadnikUSmeni>();
        }
    
        public int ID { get; set; }
        public string Adresa { get; set; }
        public System.DateTime DatumIVreme { get; set; }
        public TipIntervencijeEnum Tip { get; set; }
        public int OpstinaID { get; set; }
    
        public virtual Uvidjaj Uvidjaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadnikUSmeni> RadniciSaSmenama { get; set; }
        public virtual Opstina Opstina { get; set; }
    }
}
