//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        public Radnik()
        {
        }

        public Radnik(Radnik radnik)
        {
            this.Ime = radnik.Ime;
            this.Prezime = radnik.Prezime;
            this.JMBG = radnik.JMBG;
            this.Godina_Staza = radnik.Godina_Staza;
            this.Radno_Mesto = radnik.Radno_Mesto;
        }

        public Radnik(int jMBG, string ime, string prezime, int radno_Mesto, int godina_Staza)
        {
            JMBG = jMBG;
            Ime = ime;
            Prezime = prezime;
            Radno_Mesto = radno_Mesto;
            Godina_Staza = godina_Staza;
        }

        public int JMBG { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int Radno_Mesto { get; set; }
        public int Godina_Staza { get; set; }
        public int VatrogasnaJedinicaId_VSJ { get; set; }
        public int SmenaSmenaId { get; set; }
    
        public virtual VatrogasnaJedinica VatrogasnaJedinica { get; set; }
        public virtual Smena Smena { get; set; }
    }
}
