//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadnikUSmeni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RadnikUSmeni()
        {
            this.Intervencije = new HashSet<Intervencija>();
        }
    
        public int ID { get; set; }
        public System.DateTime DatumPocetkaRada { get; set; }
        public Nullable<System.DateTime> DatumKrajaRada { get; set; }
        public int RadnikID { get; set; }
        public int SmenaID { get; set; }
    
        public virtual Radnik Radnik { get; set; }
        public virtual Smena Smena { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervencija> Intervencije { get; set; }
    }
}
