//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tehnicko_Vozilo : Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tehnicko_Vozilo()
        {
            this.Tehnicka_Intervencija = new HashSet<Tehnicka_Intervencija>();
        }

        public Tehnicko_Vozilo(string marka, string model, int tip, int godiste, double nosivost, int? id_VatrogasneJedinice) : base( marka, model, tip, godiste, nosivost, id_VatrogasneJedinice)
        {
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tehnicka_Intervencija> Tehnicka_Intervencija { get; set; }
    }
}
