//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    
    public enum TipAlataEnum : int
    {
        TehnickiAlat = 0,
        ProtivPozarniAlat = 1,
        AlatOpsteNamene = 2
    }
}
