//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uvidjaj
    {
        public int ID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Tekst_Zapisnika { get; set; }
        public int InspektorID { get; set; }
    
        public virtual Inspektor Inspektor { get; set; }
        public virtual Intervencija Intervencija { get; set; }
    }
}
