//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;

    public partial class Vozac : Radnik
    {
        public Vozac()
        {
        }

        public Vozac(int jMBG, string ime, string prezime, int radno_Mesto, int godina_Staza) : base(jMBG, ime, prezime, radno_Mesto, godina_Staza)
        {
        }
    }
}
