//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozilo()
        {
            this.Alati = new HashSet<Alat>();
        }
    
        public int ID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public TipVozila Tip { get; set; }
        public int Godiste { get; set; }
        public double Nosivost { get; set; }
        public Nullable<int> Id_VatrogasneJedinice { get; set; }
    
        public virtual VatrogasnaJedinica VatrogasnaJedinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alat> Alati { get; set; }
    }
}
