//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervencije_VatrogasnihJedinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisnik
    {
        public int ZapisnikId { get; set; }
        public string Tekst_Zapisnika { get; set; }
    
        public virtual Uvidjaj Uvidjaj { get; set; }
    }
}
